---
- name: MGMT IP Block Split
  set_fact: 
    ip_subnet: "{{ova_builds_var.mgmt_ip_block.split('.')[0]}}.{{ova_builds_var.mgmt_ip_block.split('.')[1]}}.{{ova_builds_var.mgmt_ip_block.split('.')[2]}}"
    ip_last_octet: "{{ova_builds_var.mgmt_ip_block.split('.')[3]}}"
    ip_prefix: "{{ova_builds_var.mgmt_ip_subnet_prefix}}"


- name: Add Cloud-Init Customization (IP/GW/Passwords)
  include_tasks: cloud_init.yml
  loop: "{{ range(1, ova_builds_var.build_count + 1) }}"
  loop_control:
    loop_var: seq_item
  vars:
    sequence_number: "{{ seq_item }}"
