---
- name: MGMT IP Block Split
  set_fact: 
    ip_subnet: "{{ova_builds_var.mgmt_ip_block.split('.')[0]}}.{{ova_builds_var.mgmt_ip_block.split('.')[1]}}.{{ova_builds_var.mgmt_ip_block.split('.')[2]}}"
    ip_last_octet: "{{ova_builds_var.mgmt_ip_block.split('.')[3]}}"
    ip_prefix: "{{ova_builds_var.mgmt_ip_subnet_prefix}}"


- name: Add Cloud-Init Customization (IP/GW/Passwords)
  include_tasks: cloud_init.yml
  loop: "{{ range(1, ova_builds_var.build_count + 1) }}"
  loop_control:
    loop_var: seq_item
  vars:
    sequence_number: "{{ seq_item }}"


# - name: Add Cloud-Init Customization (IP/GW/Passwords) 
#   include_tasks: guest_cust.yml
#   with_sequence: "start=1 count={{ova_builds_var.build_count}} format=%.3d"
#   loop_control:
#     loop_var: ova_builds_var



# - name: Read file and modify with ansible variables
#   set_fact:
#     metadata: "{{ lookup('template','metadata.yml', split_lines=False)  | from_yaml}}"
#     userdata: "{{ lookup('template','userdata.yml', split_lines=False) | from_yaml}}"
#   with_sequence: "start=1 count={{ova_builds_var.build_count}} format=%.3d"

# - debug:
#     var: metadata

# - debug:
#     var: userdata

# - name: re-encode metadata and userdata into base64
#   set_fact:
#     base64_metadata: "{{ metadata | to_nice_yaml | b64encode  }}"
#     base64_userdata: "I2Nsb3VkLWNvbmZpZyAK{{ userdata | to_nice_yaml | b64encode }}"

# - debug:
#     var: base64_userdata

# # - name: fix ending and add script
# #   set_fact:
# #     base64_userdata: "{{ base64_userdata [:-1] }}" 

# - debug:
#     var: base64_metadata

# - debug:
#     var: base64_userdata


  # - name: Manipulate vApp properties
  #   community.vmware.vmware_guest:
  #     hostname: "{{ vcenter_hostname }}"
  #     username: "{{ vcenter_username }}"
  #     password: "{{ vcenter_password }}"
  #     validate_certs: no
  #     name: "{{ vm_hostname }}{{ova_builds_var.tmpl_name}}-{{item}}"
  #     state: present
  #     vapp_properties:
  #       - id: net.mgmt.addr
  #         type: string
  #         value: "{{ip_subnet}}.{{ip_last_octet |int + item |int }}/{{ova_builds_var.mgmt_ip_subnet_prefix}}"
  #       - id: net.mgmt.gw
  #         type: string
  #         value: "{{ova_builds_var.mgmt_gw}}"
  #       - id: user.root.pwd
  #         type: password
  #         value: "{{f5_pass}}"
  #       - id: user.admin.pwd
  #         type: password
  #         value: "{{f5_pass}}"
  #   delegate_to: localhost
  #   with_sequence: "start=1 count={{ova_builds_var.build_count}} format=%.3d"
