---

 - name: Provision VM from Template 
   include_tasks: clone_f5_vm.yml
   with_items: "{{ f5_ova_builds }}"
   loop_control:
     loop_var: ova_builds_var 

 - name: Add Cloud-Init Customization (IP/GW/Passwords) 
   include_tasks: guest_cust.yml
   with_items: "{{ f5_ova_builds }}"
   loop_control:
     loop_var: ova_builds_var

 - name: Power ON VMs
   include_tasks: power_on.yml
   with_items: "{{ f5_ova_builds }}"
   loop_control:
     loop_var: ova_builds_var